### ISSUE TITLE
Diagram Editor: Positioning of editors inside boxes doesn't work

### ISSUE THREAD

**Issue by RobertWalterU3d** [JetBrains/MPS-extensions#295]
When my diagram boxes contain slightly less trivial editors, the positioning is all messed up:
![image](https://user-images.githubusercontent.com/63954267/81268524-510be300-9048-11ea-9615-765f38b4176b.png)

The little blue box next to the vertical list of resources indicates the property cell that should be positioned in the selected diagram box, but it does not seem to consider the relative position of the diagram itself.
For comparison, the second green box containing "Something" is of the same concept type, at it's property cell is positioned correctly, since the collection below is empty and only shows the empty cell. this is the editor in question:
![image](https://user-images.githubusercontent.com/63954267/81268928-e1e2be80-9048-11ea-83d3-50d34ea523b8.png)

I also add boxes for each element of the "effects" collection to the diagram, and its content is a smart reference, which unfortunately also positions the Cell incorrectly (blue box with red text). 
Also, my editor does not have any styling, I don't know why the text is red.

The corresponding editor for the blue boxes ("effects") is just this:
![image](https://user-images.githubusercontent.com/63954267/81269223-4ef65400-9049-11ea-8668-64bed40de7a1.png)

**Comment by RobertWalterU3d** [comment]
I guess the problems I observe are due to the erroneous state in the model.
What I actually would like to do is to include some sort of interaction to the diagram that allows the user to add children to the green nodes by a simple interaction, like a button press. But adding swing components to the editor results in the same problem:
![DiagramLayoutIssue](https://user-images.githubusercontent.com/63954267/81270526-28d1b380-904b-11ea-943b-37117cf02ec6.gif)

The buttons seem not to consider the relative position of the diagram, nor does the box width consider the button's width resize.

**Comment by bkolb** [comment]
I have a similar issue. It is not visible in the editor, but when I create a screenshot (using the mbeddr api) I see a similar issue

**Comment by slisson** [comment]
Please try now. These issues are hard to reproduce so I had to guess and don't know if I fixed it.

**Comment by bkolb** [comment]
Hi, I tried today and I still see the issue when I take a screenshot of my diagram

**Comment by alexanderpann** [comment]
I'll close the issue as it is not reproducible anymore. It seems to be fixed. Please reopen if the issue persists.
