### ISSUE TITLE
Incremental build fails with a generic error "Make was not successful"

### ISSUE THREAD

**Issue by eugenschindler** [JetBrains/MPS-extensions#426]
When I run ./gradlew for a second time, I consistently get the following exception during build:
![Screenshot from 2021-07-09 18-06-11](https://user-images.githubusercontent.com/6429350/125107617-4f70fb80-e0e1-11eb-8bb1-b39fa57b66b2.png)
When I clean the tree completely (git clean -xfd) and run ./gradlew, the build works. But if I run ./gradlew again, then the exception occurs consistently.
Using Ubuntu 20.04.2 LTS.

**Comment by sergej-koscejev** [comment]
Can you configure the build to pass -Dmps.ant.log=info to Ant and see if you get more information?

**Comment by coolya** [comment]
I don't thin the illegal reflective access warning has anything to do with the problem. We see this since forever. 
To me this looks like one of these old problems that when the MPS make task has no models to generator then it fails.

The problem here is that all untouched models are filtered out by MPS and then the make task gets an empty list of models and fails with this error. There is nothing we can do about this in this repo except for completely disabling the incremental build.

**Comment by eugenschindler** [comment]
@sergej-koscejev, sure, the output of idea.log including the info loggings is posted below (personally, I cannot see anything suspicious, but that is because I'm not an expert in this specific area and everything looks suspicious to me).

@coolya: thanks for quickly pointing out the culprit. Is there already some YouTrack issue running for this problem? I.e. is JetBrains aware of this issue?

2021-07-14 09:19:17,174 [      0]   INFO - jetbrains.mps.tool.environment.MpsEnvironment - Creating MPS environment 
2021-07-14 09:19:17,344 [    170]   WARN - jetbrains.mps.tool.environment.PlatformPlugins - Could not detect id for plugin at /home/eugen/repo/MPS-extensions/build/mps/lib/mps-workbench.jar 
2021-07-14 09:19:17,355 [    181]  ERROR - jetbrains.mps.tool.environment.EnvironmentBase - The macro 'samples_home' to non-existent location 
2021-07-14 09:19:17,362 [    188]   INFO - jetbrains.mps.tool.environment.EnvironmentBase - Initializing libraries 
2021-07-14 09:19:17,409 [    235]   INFO - jetbrains.mps.library.LibraryInitializer - Adding libraries from SetLibraryContributor 
2021-07-14 09:19:17,409 [    235]   INFO - jetbrains.mps.library.LibraryInitializer - Adding libraries from SetLibraryContributor 
2021-07-14 09:19:17,417 [    243]   INFO - jetbrains.mps.library.LibraryInitializer - Loading 226 libraries 
2021-07-14 09:19:20,999 [   3825]   INFO - jetbrains.mps.library.LibraryInitializer - Library update is finished 
2021-07-14 09:19:23,174 [   6000]   INFO - jetbrains.mps.classloading.ModuleUpdater - Classloading refresh took 2.167 s 
2021-07-14 09:19:23,216 [   6042]   WARN - jetbrains.mps.classloading.ModulesWatcher - 1 modules are marked as invalid roots for class loading out of 280 modules [totally in the repository]: 
2021-07-14 09:19:23,217 [   6043]   WARN - jetbrains.mps.classloading.ModulesWatcher - jetbrains.mps.vcs.mergehints.plugin [solution] has got an absent dependency problem and therefore was marked invalid for class loading: The dependency in jetbrains.mps.vcs.mergehints.plugin [solution] cannot be resolved {Default} cae9c33a-938f-42e8-8f0f-26f001c0af63(jetbrains.mps.ide.devkit.editor) 
2021-07-14 09:19:23,221 [   6047]   INFO - jetbrains.mps.classloading.ModulesWatcher - Totally 1 modules are marked invalid for class loading: 
2021-07-14 09:19:23,222 [   6048]   INFO - jetbrains.mps.classloading.ModulesWatcher - f3e1e6f1-1de5-4ca2-a0b2-25f6530686ef(jetbrains.mps.vcs.mergehints.plugin) 
2021-07-14 09:19:23,771 [   6597]   INFO - jetbrains.mps.tool.environment.MpsEnvironment - Creating an empty project 
2021-07-14 09:19:23,773 [   6599]   INFO - jetbrains.mps.tool.environment.EnvironmentBase - Opening a new project 
2021-07-14 09:19:23,778 [   6604]   INFO - jetbrains.mps.project.ProjectModuleLoader - Loading modules... 
2021-07-14 09:19:23,778 [   6604]   INFO - jetbrains.mps.project.ProjectModuleLoader - Modules are loaded: 0 new; 0 removed 
2021-07-14 09:19:23,779 [   6605]   INFO - jetbrains.mps.project.ProjectBase - Project 'mpstemp18114645883734158414' is opened 
2021-07-14 09:19:24,048 [   6874]   WARN - jetbrains.mps.vfs.iofs.jar.JarIoFileSystem - Requested jar file does not exist /home/eugen/repo/MPS-extensions/build/mps/lib/jackson-databind-2.10.2.jar 
2021-07-14 09:19:24,048 [   6874]   WARN - jetbrains.mps.vfs.iofs.jar.JarIoFileSystem - Requested jar file does not exist /home/eugen/repo/MPS-extensions/build/mps/lib/jackson-annotations-2.10.2.jar 
2021-07-14 09:19:24,048 [   6874]   WARN - jetbrains.mps.vfs.iofs.jar.JarIoFileSystem - Requested jar file does not exist /home/eugen/repo/MPS-extensions/build/mps/lib/jackson-core-2.10.2.jar 
2021-07-14 09:19:24,090 [   6916]   WARN - jetbrains.mps.persistence.ModelSourceRootWalker - Source root 'Path [LocalFile(/home/eugen/repo/MPS-extensions/code/shadowmodels/solutions/de.q60.mps.collections.libs/models)]' does not exist, cannot traverse! 
2021-07-14 09:19:24,090 [   6916]   WARN - jetbrains.mps.persistence.DefaultModelRoot - Models have not been found within the Path [LocalFile(/home/eugen/repo/MPS-extensions/code/shadowmodels/solutions/de.q60.mps.collections.libs/models)] 
2021-07-14 09:19:24,141 [   6967]   WARN - jetbrains.mps.persistence.ModelSourceRootWalker - Source root 'Path [LocalFile(/home/eugen/repo/MPS-extensions/code/model-api/org.modelix.model.api/models)]' does not exist, cannot traverse! 
2021-07-14 09:19:24,141 [   6967]   WARN - jetbrains.mps.persistence.DefaultModelRoot - Models have not been found within the Path [LocalFile(/home/eugen/repo/MPS-extensions/code/model-api/org.modelix.model.api/models)] 
2021-07-14 09:19:24,830 [   7656]   INFO - jetbrains.mps.classloading.ModuleUpdater - Classloading refresh took 0.680 s 
2021-07-14 09:19:24,864 [   7690]   WARN - jetbrains.mps.classloading.ModulesWatcher - 3 modules are marked as invalid roots for class loading out of 351 modules [totally in the repository]: 
2021-07-14 09:19:24,865 [   7691]   WARN - jetbrains.mps.classloading.ModulesWatcher - de.slisson.mps.conditionalEditor/ [generator] has got an absent dependency problem and therefore was marked invalid for class loading: The dependency in de.slisson.mps.conditionalEditor/ [generator] cannot be resolved {Runtime} f0fff802-6d26-4d2e-b89d-391357265626(de.slisson.mps.hacks.editor) 
2021-07-14 09:19:24,865 [   7691]   WARN - jetbrains.mps.classloading.ModulesWatcher - jetbrains.mps.vcs.mergehints.plugin [solution] has got an absent dependency problem and therefore was marked invalid for class loading: The dependency in jetbrains.mps.vcs.mergehints.plugin [solution] cannot be resolved {Default} cae9c33a-938f-42e8-8f0f-26f001c0af63(jetbrains.mps.ide.devkit.editor) 
2021-07-14 09:19:24,865 [   7691]   WARN - jetbrains.mps.classloading.ModulesWatcher - de.itemis.mps.tooltips/ [generator] has got an absent dependency problem and therefore was marked invalid for class loading: The dependency in de.itemis.mps.tooltips/ [generator] cannot be resolved {Runtime} 0022e9df-2136-4ef8-81b2-08650aeb1dc7(de.itemis.mps.tooltips.runtime) 
2021-07-14 09:19:24,865 [   7691]   INFO - jetbrains.mps.classloading.ModulesWatcher - Totally 3 modules are marked invalid for class loading: 
2021-07-14 09:19:24,865 [   7691]   INFO - jetbrains.mps.classloading.ModulesWatcher - 4c7e6b88-d386-40ea-a53c-f652375c21a9(de.slisson.mps.conditionalEditor#2877762237605071651) 
2021-07-14 09:19:24,865 [   7691]   INFO - jetbrains.mps.classloading.ModulesWatcher - f3e1e6f1-1de5-4ca2-a0b2-25f6530686ef(jetbrains.mps.vcs.mergehints.plugin) 
2021-07-14 09:19:24,865 [   7691]   INFO - jetbrains.mps.classloading.ModulesWatcher - 091ef3ba-305a-4257-ac3b-6c5daacb61ee(de.itemis.mps.tooltips#7561794385526429391) 
2021-07-14 09:19:26,572 [   9398]   INFO - jetbrains.mps.classloading.ModuleUpdater - Classloading refresh took 0.835 s 
2021-07-14 09:19:26,605 [   9431]   WARN - jetbrains.mps.classloading.ModulesWatcher - 1 modules are marked as invalid roots for class loading out of 399 modules [totally in the repository]: 
2021-07-14 09:19:26,605 [   9431]   WARN - jetbrains.mps.classloading.ModulesWatcher - jetbrains.mps.vcs.mergehints.plugin [solution] has got an absent dependency problem and therefore was marked invalid for class loading: The dependency in jetbrains.mps.vcs.mergehints.plugin [solution] cannot be resolved {Default} cae9c33a-938f-42e8-8f0f-26f001c0af63(jetbrains.mps.ide.devkit.editor) 
2021-07-14 09:19:26,605 [   9431]   INFO - jetbrains.mps.classloading.ModulesWatcher - Totally 1 modules are marked invalid for class loading: 
2021-07-14 09:19:26,605 [   9431]   INFO - jetbrains.mps.classloading.ModulesWatcher - f3e1e6f1-1de5-4ca2-a0b2-25f6530686ef(jetbrains.mps.vcs.mergehints.plugin) 
2021-07-14 09:19:27,427 [  10253]   INFO - jetbrains.mps.classloading.ModuleUpdater - Classloading refresh took 0.175 s 
2021-07-14 09:19:27,463 [  10289]   WARN - jetbrains.mps.classloading.ModulesWatcher - 1 modules are marked as invalid roots for class loading out of 412 modules [totally in the repository]: 
2021-07-14 09:19:27,463 [  10289]   WARN - jetbrains.mps.classloading.ModulesWatcher - jetbrains.mps.vcs.mergehints.plugin [solution] has got an absent dependency problem and therefore was marked invalid for class loading: The dependency in jetbrains.mps.vcs.mergehints.plugin [solution] cannot be resolved {Default} cae9c33a-938f-42e8-8f0f-26f001c0af63(jetbrains.mps.ide.devkit.editor) 
2021-07-14 09:19:27,463 [  10289]   INFO - jetbrains.mps.classloading.ModulesWatcher - Totally 1 modules are marked invalid for class loading: 
2021-07-14 09:19:27,463 [  10289]   INFO - jetbrains.mps.classloading.ModulesWatcher - f3e1e6f1-1de5-4ca2-a0b2-25f6530686ef(jetbrains.mps.vcs.mergehints.plugin) 
2021-07-14 09:19:27,959 [  10785]   INFO - jetbrains.mps.classloading.ModuleUpdater - Classloading refresh took 0.271 s 
2021-07-14 09:19:27,997 [  10823]   WARN - jetbrains.mps.classloading.ModulesWatcher - 1 modules are marked as invalid roots for class loading out of 422 modules [totally in the repository]: 
2021-07-14 09:19:27,998 [  10824]   WARN - jetbrains.mps.classloading.ModulesWatcher - jetbrains.mps.vcs.mergehints.plugin [solution] has got an absent dependency problem and therefore was marked invalid for class loading: The dependency in jetbrains.mps.vcs.mergehints.plugin [solution] cannot be resolved {Default} cae9c33a-938f-42e8-8f0f-26f001c0af63(jetbrains.mps.ide.devkit.editor) 
2021-07-14 09:19:27,998 [  10824]   INFO - jetbrains.mps.classloading.ModulesWatcher - Totally 1 modules are marked invalid for class loading: 
2021-07-14 09:19:27,998 [  10824]   INFO - jetbrains.mps.classloading.ModulesWatcher - f3e1e6f1-1de5-4ca2-a0b2-25f6530686ef(jetbrains.mps.vcs.mergehints.plugin) 
2021-07-14 09:19:28,315 [  11141]   INFO - jetbrains.mps.classloading.ModuleUpdater - Classloading refresh took 0.103 s 
2021-07-14 09:19:28,351 [  11177]   WARN - jetbrains.mps.classloading.ModulesWatcher - 1 modules are marked as invalid roots for class loading out of 433 modules [totally in the repository]: 
2021-07-14 09:19:28,351 [  11177]   WARN - jetbrains.mps.classloading.ModulesWatcher - jetbrains.mps.vcs.mergehints.plugin [solution] has got an absent dependency problem and therefore was marked invalid for class loading: The dependency in jetbrains.mps.vcs.mergehints.plugin [solution] cannot be resolved {Default} cae9c33a-938f-42e8-8f0f-26f001c0af63(jetbrains.mps.ide.devkit.editor) 
2021-07-14 09:19:28,351 [  11177]   INFO - jetbrains.mps.classloading.ModulesWatcher - Totally 1 modules are marked invalid for class loading: 
2021-07-14 09:19:28,351 [  11177]   INFO - jetbrains.mps.classloading.ModulesWatcher - f3e1e6f1-1de5-4ca2-a0b2-25f6530686ef(jetbrains.mps.vcs.mergehints.plugin) 
2021-07-14 09:19:28,511 [  11337]   INFO - jetbrains.mps.classloading.ModuleUpdater - Classloading refresh took 0.037 s 
2021-07-14 09:19:28,534 [  11360]   WARN - jetbrains.mps.classloading.ModulesWatcher - 1 modules are marked as invalid roots for class loading out of 280 modules [totally in the repository]: 
2021-07-14 09:19:28,534 [  11360]   WARN - jetbrains.mps.classloading.ModulesWatcher - jetbrains.mps.vcs.mergehints.plugin [solution] has got an absent dependency problem and therefore was marked invalid for class loading: The dependency in jetbrains.mps.vcs.mergehints.plugin [solution] cannot be resolved {Default} cae9c33a-938f-42e8-8f0f-26f001c0af63(jetbrains.mps.ide.devkit.editor) 
2021-07-14 09:19:28,534 [  11360]   INFO - jetbrains.mps.classloading.ModulesWatcher - Totally 1 modules are marked invalid for class loading: 
2021-07-14 09:19:28,534 [  11360]   INFO - jetbrains.mps.classloading.ModulesWatcher - f3e1e6f1-1de5-4ca2-a0b2-25f6530686ef(jetbrains.mps.vcs.mergehints.plugin)

**Comment by sergej-koscejev** [comment]
Yes, the logs don't show anything suspicious. I think Kolja is right about the root cause.

**Comment by wsafonov** [comment]
I'm not sure that the incremental build is the actual problem here. We are using it in a different project (however built with maven) and there it works just fine. We see output like this (starting with the second build after git clean) where you obviously have no models to generate and the build runs w/o breaking:

```
 [generate] Generating: strict mode is on, parallel generation is on (8 threads), in-place is off, warnings are on, static references to replace dynamic is on, skip unmodified models is on
 [generate] 9621 [main] INFO jetbrains.mps.tool.environment.MpsEnvironment  - Creating an empty project
 [generate] 9623 [main] INFO jetbrains.mps.tool.environment.EnvironmentBase  - Opening a new project
 [generate] 9628 [main] INFO jetbrains.mps.project.ProjectModuleLoader  - Loading modules...
 [generate] 9629 [main] INFO jetbrains.mps.project.ProjectModuleLoader  - Modules are loaded: 0 new; 0 removed
 [generate] 9630 [main] INFO jetbrains.mps.project.ProjectBase  - Project 'mpstemp15725390493838936796' is opened
 [generate] Loaded module datev.steuer.dsl.build [solution]
 [generate] 9777 [main] INFO jetbrains.mps.classloading.ModuleUpdater  - Classloading refresh took 0,099 s
 [generate] 9822 [main] INFO jetbrains.mps.classloading.ModulesWatcher  - Totally 0 modules are marked invalid for class loading.
 [generate] Generating:
 [generate]     datev.steuer.dsl.build [solution]
 [generate] Found 0 modified models out of 2 total models.
 [generate] No models to generate. Skipping generation.
 [generate] 9930 [main] INFO jetbrains.mps.classloading.ModuleUpdater  - Classloading refresh took 0,058 s
 [generate] 9963 [main] INFO jetbrains.mps.classloading.ModulesWatcher  - Totally 0 modules are marked invalid for class loading.
 [generate] 20083 [main] INFO jetbrains.mps.classloading.ModuleUpdater  - Classloading refresh took 0,002 s
 [generate] 20083 [main] INFO jetbrains.mps.classloading.ModulesWatcher  - Totally 0 modules are marked invalid for class loading.
```

**Comment by coolya** [comment]
@wsafonov in your case you are generating a single solution the build one. For what every reason MPS often thinks those models have changed.

The problem is with [BaseGeneratorWorker](https://github.com/JetBrains/MPS/blob/78a8983d975c3177461ae2553fd253bdc63baab6/core/tool/builder/source_gen/jetbrains/mps/tool/builder/make/BaseGeneratorWorker.java#L98) which assumes it has failed when the result is null and the [CoreMakeTask]( https://github.com/JetBrains/MPS/blob/78a8983d975c3177461ae2553fd253bdc63baab6/core/make-runtime/solutions/jetbrains.mps.make/source_gen/jetbrains/mps/make/service/CoreMakeTask.java#L69) that doesn't set a result if the make sequence is empty. 

@eugenschindler I have no clue. There simply no way to figure out if it has been reported to youtrack with that amount of open issues in there.

**Comment by wsafonov** [comment]
@coolya well, that was just an example with build solutions. With the main part of the buid where there are no build solutions in the generation it also works, even if there no changed models at all according to the log output. But maybe it is then something similar as with build solutions - MPS still thinks some models are changed even if it says differently in the logs. Anyway it's clearly an MPS bug.

**Comment by wsafonov** [comment]
I have reported this problem [here](https://youtrack.jetbrains.com/issue/MPS-33541). Feel free to upvote.

**Comment by artem-tikhomirov** [comment]
@coolya could you please elaborate which particular piece of BaseGeneratorWorker is flawed? If there're no models to generate, there has to be an info message "No models to generate..." as in https://github.com/JetBrains/MPS-extensions/issues/426#issuecomment-879890988. Therefore, it's unlikely make fails due to 'no models' scenario.
 Message "Make was not successful" indicates there were models with changes, and an attempt to make them didn't complete as expected.  It has to be an error or an exception during make (not necessarily generate, there's also textgen and compile). I wonder why there's nothing in the log then. @eugenschindler, I don't see "Generating: strict mode is ..." message in your log, nor there's "[generate]" prefix, could you please check the log relates to the failing generate task? There has to be few info messages prior to "Make was not successful".

**Comment by wsafonov** [comment]
@artem-tikhomirov here is the exception stacktrace from the private project:

```
 [generate] Found 1 modified models out of 340 total models.
 [generate] java.lang.NullPointerException
 [generate]     at jetbrains.mps.tool.builder.make.BaseGeneratorWorker.generate(BaseGeneratorWorker.java:98)
 [generate]     at jetbrains.mps.tool.builder.make.GeneratorWorker.work(GeneratorWorker.java:55)
 [generate]     at jetbrains.mps.tool.builder.WorkerBase.workFromMain(WorkerBase.java:127)
 [generate]     at jetbrains.mps.tool.builder.make.GeneratorWorker.main(GeneratorWorker.java:80)
 [generate]
```

Not sure if it's the same in this project, but maybe this would give you at least an idea where and what to look for.

**Comment by artem-tikhomirov** [comment]
@wsafonov , this NPE has been fixed in 2020.3, I suppose.

**Comment by kbirken** [comment]
Could easily reproduce this issue (or something similar) with iets3.core master which uses MPS 2021.1. Problem is still there, unfortunately. The second gradle-build (after a first complete gradle-build for a fresh repo) fails with the following exception:

```
generate:
     [echo] generating
 [generate] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
 [generate] WARNING: All illegal access operations will be denied in a future release
 [generate] Log4j is initialized by MPS from the configuration file /Users/birken/Documents/pgm/iets3/iets3.core/build/mps/bin/log.xml
 [generate] java.lang.RuntimeException: ****************************************************************************************************
 [generate] 1 errors during generation:
 [generate] Make was not successful
 [generate] ****************************************************************************************************
 [generate]     at jetbrains.mps.tool.builder.WorkerBase.failBuild(WorkerBase.java:174)
 [generate]     at jetbrains.mps.tool.builder.make.BaseGeneratorWorker.showStatistic(BaseGeneratorWorker.java:71)
 [generate]     at jetbrains.mps.tool.builder.make.GeneratorWorker.work(GeneratorWorker.java:75)
 [generate]     at jetbrains.mps.tool.builder.WorkerBase.workFromMain(WorkerBase.java:127)
 [generate]     at jetbrains.mps.tool.builder.make.GeneratorWorker.main(GeneratorWorker.java:80)
 [generate]
```

Copied it from [the original issue](https://github.com/IETS3/iets3.core/issues/625) because its repo is private. 

The stackdump is not exactly the same, may the fix from 2020.3 changed the detailed behavior, but still leads to an exception.

**Comment by ftomassetti** [comment]
Same here

**Comment by wsafonov** [comment]
I have removed mention of "illegal reflective access" from the title, as it has nothing to do with the actual cause here.

**Comment by artem-tikhomirov** [comment]
If there's a sample project to reproduce the issue, I'd be glad to look into it and back port a fix up to 21.1. I suppose it's some empty model and it's 'generation required' status being flipped for the second run, but would need a project to reproduce/validate fix. If anyone got a sample ready or willing to prepare one, I'd be very grateful.

**Comment by sergej-koscejev** [comment]
This is reported in YouTrack under https://youtrack.jetbrains.com/issue/MPS-33541/Incremental-build-fails-during-generation-on-no-changed-models and I have commented there that the problem is an empty model: https://youtrack.jetbrains.com/issue/MPS-33541/Incremental-build-fails-during-generation-on-no-changed-models#focus=Comments-27-5451412.0-0

**Comment by alexanderpann** [comment]
According to the ticket, this should now be fixed.
